module Tile(Actor(..), Tile(..), GameState(..), Direction(..), standardTiles) where
import Prelude hiding(Right, Left)
-- Suppress HLint messages
{-# ANN module "HLint: Ignore Use mappend" #-}

-- TODO: Write representation convention

data Actor = Void | Player (Float, Float) | Computer (Float, Float)
data Direction = Up | Down | Left | Right
data Tile = Floor (Float, Float) [Direction] | Wall (Float, Float)
data GameState = State [Tile] Actor Actor

standardTiles = [
  Floor (-6, 6) [],
  Floor (-5, 6) [],
  Floor (-4, 6) [],
  Floor (-3, 6) [],
  Floor (-2, 6) [],
  Wall (-1, 6),
  Floor (0, 6) [],
  Floor (1, 6) [],
  Floor (2, 6) [],
  Floor (3, 6) [],
  Floor (4, 6) [],
  Floor (5, 6) [],
  Floor (6, 6) [],

  Floor (-6, 5) [],
  Wall (-5, 5),
  Wall (-4, 5),
  Wall (-3, 5),
  Floor (-2, 5) [],
  Wall (-1, 5),
  Floor (0, 5) [],
  Wall (1, 5),
  Wall (2, 5),
  Wall (3, 5),
  Wall (4, 5),
  Wall (5, 5),
  Floor (6, 5) [],

  Floor (-6, 4) [],
  Wall (-5, 4),
  Floor (-4, 4) [],
  Floor (-3, 4) [],
  Floor (-2, 4) [],
  Wall (-1, 4),
  Floor (0, 4) [],
  Floor (1, 4) [],
  Floor (2, 4) [],
  Floor (3, 4) [],
  Floor (4, 4) [],
  Floor (5, 4) [],
  Floor (6, 4) [],

  Floor (-6, 3) [],
  Wall (-5, 3),
  Wall (-4, 3),
  Wall (-3, 3),
  Floor (-2, 3) [],
  Floor (-1, 3) [],
  Floor (0, 3) [],
  Floor (1, 3) [],
  Floor (2, 3) [],
  Wall (3, 3),
  Wall (4, 3),
  Wall (5, 3),
  Floor (6, 3) [],

  Floor (-6, 2) [],
  Floor (-5, 2) [],
  Floor (-4, 2) [],
  Floor (-3, 2) [],
  Floor (-2, 2) [],
  Wall (-1, 2),
  Floor (0, 2) [],
  Floor (1, 2) [],
  Floor (2, 2) [],
  Wall (3, 2),
  Floor (4, 2) [],
  Floor (5, 2) [],
  Floor (6, 2) [],

  Floor (-6, 1) [],
  Wall (-5, 1),
  Wall (-4, 1),
  Wall (-3, 1),
  Floor (-2, 1) [],
  Floor (-1, 1) [],
  Floor (0, 1) [],
  Floor (1, 1) [],
  Floor (2, 1) [],
  Wall (3, 1),
  Floor (4, 1) [],
  Floor (5, 1) [],
  Floor (6, 1) [],

  Floor (-6, 0) [],
  Floor (-5, 0) [],
  Floor (-4, 0) [],
  Floor (-3, 0) [],
  Floor (-2, 0) [],
  Wall (-1, 0),
  Wall (0, 0),
  Wall (1, 0),
  Wall (2, 0),
  Wall (3, 0),
  Wall (4, 0),
  Wall (5, 0),
  Floor (6, 0) [],

  Wall (-6, -1),
  Wall (-5, -1),
  Wall (-4, -1),
  Wall (-3, -1),
  Floor (-2, -1) [],
  Floor (-1, -1) [],
  Floor (0, -1) [],
  Floor (1, -1) [],
  Floor (2, -1) [],
  Floor (3, -1) [],
  Floor (4, -1) [],
  Floor (5, -1) [],
  Floor (6, -1) [],

  Floor (-6, -2) [],
  Wall (-5, -2),
  Floor (-4, -2) [],
  Floor (-3, -2) [],
  Floor (-2, -2) [],
  Wall (-1, -2),
  Wall (0, -2),
  Wall (1, -2),
  Wall (2, -2),
  Wall (3, -2),
  Wall (4, -2),
  Wall (5, -2),
  Floor (6, -2) [],

  Floor (-6, -3) [],
  Wall (-5, -3),
  Wall (-4, -3),
  Wall (-3, -3),
  Floor (-2, -3) [],
  Floor (-1, -3) [],
  Floor (0, -3) [],
  Floor (1, -3) [],
  Floor (2, -3) [],
  Floor (3, -3) [],
  Floor (4, -3) [],
  Wall (5, -3),
  Floor (6, -3) [],

  Floor (-6, -4) [],
  Floor (-5, -4) [],
  Wall (-4, -4),
  Floor (-3, -4) [],
  Floor (-2, -4) [],
  Floor (-1, -4) [],
  Wall (0, -4),
  Wall (1, -4),
  Floor (2, -4) [],
  Floor (3, -4) [],
  Floor (4, -4) [],
  Wall (5, -4),
  Floor (6, -4) [],

  Floor (-6, -5) [],
  Floor (-5, -5) [],
  Wall (-4, -5),
  Floor (-3, -5) [],
  Floor (-2, -5) [],
  Floor (-1, -5) [],
  Floor (0, -5) [],
  Wall (1, -5),
  Wall (2, -5),
  Wall (3, -5),
  Wall (4, -5),
  Wall (5, -5),
  Floor (6, -5) [],

  Floor (-6, -6) [],
  Floor (-5, -6) [],
  Floor (-4, -6) [],
  Floor (-3, -6) [],
  Floor (-2, -6) [],
  Floor (-1, -6) [],
  Floor (0, -6) [],
  Floor (1, -6) [],
  Floor (2, -6) [],
  Floor (3, -6) [],
  Floor (4, -6) [],
  Floor (5, -6) [],
  Floor (6, -6) []
  ]
